export const LOAD_GROUPS = '@SEND_EMAIL/LOAD_GROUPS'
export const LOAD_ATTRIBUTES = '@SEND_EMAIL/LOAD_ATTRIBUTES'

export const LOAD_RECEIVER_EMAIL = '@SEND_EMAIL/LOAD_RECEIVER_EMAIL'
export const LOAD_RECEIVER_EMAIL_SELECTED = '@SEND_EMAIL/LOAD_RECEIVER_EMAIL_SELECTED'

export const SEND_EMAIL = '@SEND_EMAIL/SEND_EMAIL'
