export const LOAD_PROFILE = '@COURSE/LOAD_PROFILE'
export const ERROR_USER_EXPIRED_TRIAL = 'ERROR_USER_EXPIRED_TRIAL'
export const ERROR_COMPANY_HAS_CANCELLATION = 'ERROR_COMPANY_HAS_CANCELLATION'
export const ERROR_USER_EXPIRED_PAYMENT = 'ERROR_USER_EXPIRED_PAYMENT'
