const SUMMARY_1380 = {
  layout_top: '120px 40% calc(60% - 165px)',
  height_title: '25px',
  fs_title: '13px',
  scaleIcon: 0.8,
  translateIcon: '4px,-4px',
  gapOverviewBasic: '14px',
  jusOverviewBasic: 'flex-start',
  avatar: {
    whAvatar: '80px',
    whStatus: '32px',
    fsContent: '12px',
    gapStatus: '12px',
    ptStatus: '8px',
    gapContent: 1,
  },
  overview: {
    fsLine: '9px',
    wBoxLine: '70px',
    gapLayout: 1,
    mbLayout: 1,
    lineHeightContent: '13px',
    lineHeightContentDate: '19px',
    lineHeightContentBox: '16px',
    heightContentDate: '20px',
    heightContent: '12px',
  },
  basicInfo: {
    heightLayout: '198px',
    fsContent: '8px',
    mgContent: '4px',
    heightBox: '18px',
    lineHeightBox: '17px',
    widthBox: '32px',
    fsBox: '12px',
    heightDes: '40px',
    heightEs: '16px',
    lineHeightEs: '14px',
    widthEs: '45px',
  },
  projectInfo: {
    heightLayout: '198px',
    fsContent: '8px',
    gapLayout: '2px',
    heightDes: '42px',
    heightBox: '18px',
    widthBox: '32px',
    fsBox: '9px',
    lineHeightBox: '12px',
  },
};

export { SUMMARY_1380 };
