const LAYOUT_1280 = {
  widthFull: 170,
  widthHideSidebar: 110,
  heightNavbar: 60,
  fsTitle: 32,
  mrNavItem: '5px auto',
  plIcon: 5,
  pyListItem: 2,
  pxListItem: 3,
  mrIcon: 2,
  fsList: '12px',
  heightBoxInfo: 48,
};

const SUMMARY_1280 = {
  layout_top: '105px 40% calc(60% - 165px)',
  layout_bot: '35% 35% calc(30% - 60px)',
  height_title: '22px',
  fs_title: '12px',
  scaleIcon: 0.7,
  translateIcon: '15px,-5px',
  gapOverviewBasic: '10px',
  jusOverviewBasic: 'flex-start',
  gapLayout: '10px',
  avatar: {
    whAvatar: '65px',
    whStatus: '26px',
    fsContent: '10px',
    gapStatus: '12px',
    ptStatus: '8px',
    gapContent: 1,
  },
  overview: {
    fsLine: '7px',
    wBoxLine: '60px',
    gapLayout: 1,
    mbLayout: '10px',
    lineHeightContent: '11px',
    lineHeightContentDate: '17px',
    lineHeightContentBox: '14px',
    heightContentDate: '18px',
    heightContent: '10px',
  },
  basicInfo: {
    heightLayout: '170px',
    fsContent: '7px',
    mgContent: '3px',
    heightBox: '16px',
    lineHeightBox: '15px',
    widthBox: '30px',
    fsBox: '8px',
    heightDes: '34px',
    heightEs: '15px',
    lineHeightEs: '15px',
    widthEs: '45px',
  },
  projectInfo: {
    heightLayout: '170px',
    fsContent: '7px',
    gapLayout: '2px',
    heightDes: '38px',
    heightBox: '16px',
    widthBox: '30px',
    fsBox: '8px',
    lineHeightBox: '10px',
  },
  policyProgress: {
    hLayout: '254px',
    fsContent: '7px',
    fsBox: '8px',
    gapBox: '3px',
    wBox: '100%',
    hDes1: '50px',
    hDes2: '72.5%',
  },
  employeeSuccess: {
    hLayout: '254px',
    fsContent: '7px',
    fsBox: '8px',
    wChart: '40%',
    hChart: '85px',
    ptChart: '5px',
    hDes1: '36px',
    hBoxValue: '14px',
    lhBoxValue: '10px',
    mbBoxValue: '0px',
    hDes2: '30px',
  },
  interviewLog: {
    hLayout: '254px',
    fsContent: '7px',
    fsBox: '8px',
    hDes: '164px',
  },
};

export { LAYOUT_1280, SUMMARY_1280 };
