const LAYOUT = {
  widthFull: 248,
  widthHideSidebar: 120,
  heightNavbar: 80,
  fsTitle: 36,
  mrNavItem: '10px auto',
  plIcon: 15,
  pyListItem: 3,
  pxListItem: 6,
  mrIcon: 4,
  fsList: '16px',
  heightBoxInfo: 56,
};

const SUMMARY = {
  layout_top: '160px 45% auto',
  layout_bot: '35% 35% auto',
  height_title: '40px',
  fs_title: '16px',
  scaleIcon: 1,
  translateIcon: 0,
  gapOverviewBasic: 2,
  jusOverviewBasic: 'space-between',
  gapLayout: '16px',
  avatar: {
    whAvatar: '134px',
    whStatus: '40px',
    fsContent: '16px',
    gapStatus: '20px',
    ptStatus: '17px',
    gapContent: 2,
  },
  overview: {
    fsLine: '12px',
    wBoxLine: '110px',
    gapLayout: 3,
    mbLayout: 3,
    lineHeightContent: '20px',
    lineHeightContentDate: '28px',
    lineHeightContentBox: '24px',
    heightContentDate: '30px',
    heightContent: '22px',
  },
  basicInfo: {
    heightLayout: '340px',
    fsContent: '10px',
    mgContent: '5px',
    heightBox: '24px',
    lineHeightBox: '24px',
    widthBox: '32px',
    fsBox: '14px',
    heightDes: '60px',
    heightEs: '20px',
    lineHeightEs: '18px',
    widthEs: '62px',
  },
  projectInfo: {
    heightLayout: '340px',
    fsContent: '10px',
    gapLayout: '6px',
    heightDes: '60px',
    heightBox: '22px',
    fsBox: '10px',
    lineHeightBox: '16px',
  },
  policyProgress: {
    hLayout: '394px',
    fsContent: '10px',
    fsBox: '10px',
    gapBox: '10px',
    wBox: '240px',
    hDes1: '95px',
    hDes2: '100%',
  },
  employeeSuccess: {
    hLayout: '394px',
    fsContent: '10px',
    fsBox: '10px',
    wChart: '40%',
    hChart: '120px',
    ptChart: '10px',
    hDes1: '60px',
    hBoxValue: '22px',
    lhBoxValue: '15px',
    mbBoxValue: '5px',
    hDes2: '36px',
  },
  interviewLog: {
    hLayout: '394px',
    fsContent: '10px',
    fsBox: '10px',
    hDes: '264px',
  },
};
export { LAYOUT, SUMMARY };
