const LIST_DEFINE_FILTERS = {
  establishmentDate: 'establishmentDates',
  endDate: 'endDates',
  departmentLevel: 'departmentLevels',
  departmentId: 'ids',
  departmentName: 'ids',
  codeListId: 'codeListIds',
  codeListName: 'codeListNames',
  codeName: 'codeNames',
  codeValue: 'codeValues',
  codeNameEn: 'codeNameEns',
  createdDatetime: 'createdDates',
  sortOrder: 'sortOrders',
  updatedUser: 'updatedBys',
  trainingCode: 'trainingCodes',
  trainingType: 'trainingTypes',
  trainingName: 'trainingNameCodes',
  compPolicyClassCode: 'compPolicyClassCodes',
  compPolicyClassName: 'compPolicyClassNameCodes',
  effectStartDate: 'effectStartDates',
  effectEndDate: 'effectEndDates',
  userCode: 'userCodes',
  role: 'roles',
  esMngPred: 'esMngPreds',
  esMngPredDescription: 'esMngPredDescriptions',
  roleName: 'roles',
  roleNameEn: 'roles',
  employeeName: 'employeeNames',
  employeeId: 'employeeIds',
  employeeNameKana: 'employeeNameKanas',
  position: 'positions',
  createdUser: 'createdBys',
  updatedDatetime: 'updatedDates',
  esMngBelong: 'esMngBelongs',
  esMngTeamLeader: 'esMngTeamLeaders',
  matterNo: 'matterNos',
  matterName: 'matterNames',
  careerId: 'careerIds',
  applicant: 'applicants',
  applyDate: 'applyDates',
  approverRequest: 'approverRequests',
  agentRequest: 'agentRequests',
  wfStatusId: 'wfStatusIds',
  '': '',
};

const LIST_FILTER_DATE = ['createdDatetime', 'updatedDatetime'];

export { LIST_DEFINE_FILTERS, LIST_FILTER_DATE };
