export const LOAD_LESSON_BY_ID = '@COURSE/LOAD_LESSON_BY_ID'
export const LOAD_LESSON_BY_ID_SUCCESS = '@COURSE/LOAD_LESSON_BY_ID_SUCCESS'
export const LOAD_LESSON_BY_ID_ERROR = '@COURSE/LOAD_LESSON_BY_ID_ERROR'

export const SUBMIT_LESSON_BY_ID = '@COURSE/SUBMIT_LESSON_BY_ID'
export const SUBMIT_LESSON_BY_ID_SUCCESS = '@COURSE/SUBMIT_LESSON_BY_ID_SUCCESS'
export const SUBMIT_LESSON_BY_ID_ERROR = '@COURSE/SUBMIT_LESSON_BY_ID_ERROR'

export const LOAD_COURSE_DETAIL = '@COURSE/LOAD_COURSE_DETAIL'
export const LOAD_COURSE_DETAIL_SUCCESS = '@COURSE/LOAD_COURSE_DETAIL_SUCCESS'
export const LOAD_COURSE_DETAIL_ERROR = '@COURSE/LOAD_COURSE_DETAIL_ERROR'

export const LOAD_COURSE_DETAIL_UNREGISRTERED = '@COURSE/LOAD_COURSE_DETAIL_UNREGISRTERED'
export const LOAD_COURSE_DETAIL_UNREGISRTERED_SUCCESS = '@COURSE/LOAD_COURSE_DETAIL_UNREGISRTERED_SUCCESS'
export const LOAD_COURSE_DETAIL_UNREGISRTERED_ERROR = '@COURSE/LOAD_COURSE_DETAIL_UNREGISRTERED_ERROR'

export const VOTE_LIKE_UNIT = '@COURSE/VOTE_LIKE_UNIT'
export const VOTE_LIKE_UNIT_SUCCESS = '@COURSE/VOTE_LIKE_UNIT_SUCCESS'

export const COUNT_VIEW_UNIT = '@COURSE/COUNT_VIEW_UNIT'
export const COUNT_VIEW_UNIT_SUCCESS = '@COURSE/COUNT_VIEW_UNIT_SUCCESS'

export const REQUEST_PASSWORD_VIDEO = '@COURSE/REQUEST_PASSWORD_VIDEO'

export const LOAD_REPOS_ERROR = '@COURSE/LOAD_REPOS_ERROR'
