// WORKSPACE_MANAGEMENT
export const GET_WORKSPACE_ALL = '@WORKSPACE_MANAGEMENT/GET_WORKSPACE_ALL'
export const DELETE_WORKSPACE = '@WORKSPACE_MANAGEMENT/DELETE_WORKSPACE'
export const LOAD_WORKSPACE_DETAIL = '@WORKSPACE_MANAGEMENT/LOAD_WORKSPACE_DETAIL'
export const DELETE_USER_WORKSPACE = '@WORKSPACE_MANAGEMENT/DELETE_USER_WORKSPACE'
export const ADD_USER_WORKSPACE = '@WORKSPACE_MANAGEMENT/ADD_USER_WORKSPACE'
export const RESET_WORKSPACES = '@WORKSPACE_MANAGEMENT/RESET_WORKSPACES'

// CREATE_WORKSPACE
export const CREATE_WORKSPACE = '@WORKSPACE_MANAGEMENT/CREATE_WORKSPACE'
export const EDIT_WORKSPACE = '@WORKSPACE_MANAGEMENT/EDIT_WORKSPACE'
export const GET_ADMINS_NISSOKEN = '@WORKSPACE_MANAGEMENT/GET_ADMINS_NISSOKEN'
export const GET_WORKSPACE_DETAIL = '@WORKSPACE_MANAGEMENT/GET_WORKSPACE_DETAIL'
