export const GET_LIST_REPORT = '@REPORT_MANAGEMENT/GET_LIST_REPORT'
export const GET_REPORT_DETAIL = '@REPORT_MANAGEMENT/GET_REPORT_DETAIL'
export const LOAD_COMMENTS_DAILY_REPORT = '@LOAD_COMMENTS_DAILY_REPORT/LOAD_COMMENTS_DAILY_REPORT'
export const RESET_LIST_REPORT = '@LOAD_COMMENTS_DAILY_REPORT/RESET_LIST_REPORT'
