export const VERIFY_PASSWORD = '@VERIFY_PASSWORD/VERIFY_PASSWORD'
export const VERIFY_PASSWORD_SUCCESS = '@VERIFY_PASSWORD/VERIFY_PASSWORD_SUCCESS'
export const VERIFY_PASSWORD_ERROR = '@VERIFY_PASSWORD/VERIFY_PASSWORD_ERROR'

export const SETTING_PASSWORD = '@VERIFY_PASSWORD/SETTING_PASSWORD'
export const SETTING_PASSWORD_SUCCESS = '@VERIFY_PASSWORD/SETTING_PASSWORD_SUCCESS'
export const SETTING_PASSWORD_ERROR = '@VERIFY_PASSWORD/UPDATE_PASSWORD_ERROR'
