export const LOAD_REPORTS = '@REPORT_PUBLISH_SETTING/LOAD_REPORTS'
export const LOAD_DETAIL_PUBLISH_REPORT = '@REPORT_PUBLISH_SETTING/LOAD_DETAIL_PUBLISH_REPORT'
export const UPDATE_DETAIL_PUBLISH_REPORT = '@REPORT_PUBLISH_SETTING/UPDATE_DETAIL_PUBLISH_REPORT'
