const KEY_FIlTER_LV1 = '[===]:';
const KEY_FILTER_LV2 = '[==]:';
const KEY_CHECKED_LV3 = '[=CKed]:';
const nameColumnsJP = {
  t_work_interview_log: '面談ログ',
  t_work_overview: '概要',
  t_work_project_info: 'プロジェクトInfo',
  t_work_empl_success: 'Employee Success軸',
  t_work_policy_prog: '方針と進捗',
  t_basic_info: '基本Info',
};

const nameColumnEn = {
  t_work_interview_log: 'Interview Log',
  t_work_overview: 'Overview',
  t_work_project_info: 'Project Info',
  t_work_empl_success: 'Employee Success',
  t_work_policy_prog: 'Policy and progress',
  t_basic_info: 'Basic info',
};

const nameColumnSub2JP = {
  interview_category: '面談カテゴリ',
  interview_responsible_person: '面談担当',
  action_required: '要対応',
  childcare_maternity_leave: '育休・産休中',
  comprehension: '理解度',
  es_manager: 'ES担当',
  leave_off: '休職中',
  not_in_operation: '未稼働中',
  overtime_flag: '残業フラグ',
  pinasa_flag: 'ピンアサフラグ',
  predecessor: '前任者',
  relationship: '関係性',
  status: 'ステータス',
  when_end: 'いつまでに',
  client: 'クライアント',
  evaluation: '評価',
  project_name: 'プロジェクト名',
  sales_in_charge: '担当営業',
  sell_team: 'チーム売',
  unit_price: '単価',
  es_status: 'ESステータス',
  career: 'キャリア',
  job_description: '仕事内容',
  money: 'お金',
  others_success: 'その他',
  relationships: '人間関係',
  work_method: '働き方',
  fiscal_year: '年度',
  tobe_fy_fiscal: 'ToBe FY Fiscal',
  risk_selection: 'Tリスク（選択）',
  birthday: '年齢',
  es_responsibility: 'ES責',
  joining_company: '入社',
  mid_career_new_graduate: '中途/新卒',
  position: '職位',
  retirement: '退職',
  retirement_date: '退職年月',
  sex: '性別',
  royalties_optional: 'ロイヤリティ',
  interview_date: '面談日付',
  interview_next_date: '次回面談予定日',
  business_category: '業務カテゴリ',
  recognition_of_person: '本人の認識',
};

const nameColumnSub2En = {
  interview_category: 'Interview category',
  interview_responsible_person: 'Interview responsible person',
  action_required: 'Action required',
  childcare_maternity_leave: 'Childcare maternity leave',
  comprehension: 'Comprehension',
  es_manager: 'ES manager',
  leave_off: 'Leave off',
  not_in_operation: 'Not in operation',
  overtime_flag: 'Overtime flag',
  pinasa_flag: 'Pinasa flag',
  predecessor: 'Predecessor',
  relationship: 'Relationship',
  status: 'Status',
  when_end: 'When_end',
  client: 'Client',
  evaluation: 'Evaluation',
  project_name: 'Project name',
  sales_in_charge: 'Sales in charge',
  sell_team: 'Sell team',
  unit_price: 'Unit price',
  es_status: 'ES status',
  career: 'Career',
  job_description: 'Job description',
  money: 'Money',
  others_success: 'Others success',
  relationships: 'Relationships',
  work_method: 'Work method',
  fiscal_year: 'Fiscal year',
  tobe_fy_fiscal: 'ToBe FY fiscal',
  risk_selection: 'Risk selection',
  birthday: 'Birthday',
  es_responsibility: 'Es responsibility',
  joining_company: 'Joining company',
  mid_career_new_graduate: 'Mid career new graduate',
  position: 'Position',
  retirement: 'Retirement',
  retirement_date: 'Retirement date',
  sex: 'Gender',
  royalties_optional: 'Royalties optional',
  interview_date: 'Interview date',
  interview_next_date: 'Interview next date',
  business_category: 'Business Category',
  recognition_of_person: 'Recognition of person',
};

const CHANGE_KEYS_FILTER = {
  interview_category: 'interviewCategoryFlag',
  interview_date: 'interviewDateFlag',
  interview_next_date: 'interviewNextDateFlag',
  interview_responsible_person: 'interviewResponsiblePersonFlag',
  action_required: 'actionRequiredFlag',
  childcare_maternity_leave: 'childcareMaternityLeaveFlag',
  comprehension: 'comprehensionFlag',
  es_manager: 'esManagerFlag',
  leave_off: 'leaveOffFlag',
  not_in_operation: 'notInOperationFlag',
  overtime_flag: 'overtimeFlag',
  pinasa_flag: 'pinasaFlag',
  predecessor: 'predecessorFlag',
  relationship: 'relationshipFlag',
  status: 'statusFlag',
  when_end: 'whenEndFlag',
  client: 'clientFlag',
  evaluation: 'evaluationFlag',
  project_name: 'projectNameFlag',
  sales_in_charge: 'salesInChargeFlag',
  sell_team: 'sellTeamFlag',
  unit_price: 'unitPriceFlag',
  es_status: 'esStatusFlag',
  career: 'careerFlag',
  job_description: 'jobDescriptionFlag',
  money: 'moneyFlag',
  others_success: 'othersSuccessFlag',
  relationships: 'relationshipsFlag',
  work_method: 'workMethodFlag',
  fiscal_year: 'fiscalYearFlag',
  tobe_fy_fiscal: 'tobeFyFiscalFlag',
  risk_selection: 'riskSelectionFlag',
  birthday: 'birthdayFlag',
  es_responsibility: 'esResponsibilityFlag',
  joining_company: 'joiningCompanyFlag',
  mid_career_new_graduate: 'midCareerNewGraduateFlag',
  position: 'positionFlag',
  retirement: 'retirementFlag',
  retirement_date: 'retirementDateFlag',
  sex: 'sexFlag',
  royalties_optional: 'royaltiesOptionalFlag',
  business_category: 'businessCategoryFlag',
  recognition_of_person: 'recognitionOfPersonFlag',
};

const listTrueFalse = [
  'action_required',
  'pinasa_flag',
  'overtime_flag',
  'leave_off',
  'childcare_maternity_leave',
  'not_in_operation',
  'es_responsibility',
];
const renderListMess = (value, text) => {
  const result = {};
  listTrueFalse.forEach((item) => {
    result[`${item}${KEY_FILTER_LV2}${value}`] = text;
  });
  return result;
};

const nameColumnSub3En = {
  null: 'Null',
  ...renderListMess('true', 'True'),
  ...renderListMess('false', 'False'),
};
const nameColumnSub3Jp = {
  null: '空白',
  ...renderListMess('true', '有'),
  ...renderListMess('false', '無'),
};
export {
  nameColumnEn,
  nameColumnsJP,
  nameColumnSub2JP,
  nameColumnSub2En,
  CHANGE_KEYS_FILTER,
  KEY_FIlTER_LV1,
  KEY_FILTER_LV2,
  KEY_CHECKED_LV3,
  nameColumnSub3En,
  nameColumnSub3Jp,
};
