export const UPLOAD_RECORDING = '@RECORDING/UPLOAD_RECORDING'
export const FOLDER_RECORDING = '@RECORDING/FOLDER_RECORDING'
export const CHECK_EXIST_FILENAME = '@RECORDING/CHECK_EXIST_FILENAME'
export const UPLOAD_S3 = '@RECORDING/UPLOAD_S3'
