export const GET_PASSWORDS = '@SETTING_PASSWORD_PLAN/GET_PASSWORDS'
export const ADD_PASSWORD = '@SETTING_PASSWORD_PLAN/ADD_PASSWORD'
export const DELETE_PASSWORD = '@SETTING_PASSWORD_PLAN/DELETE_PASSWORD'

export const CHANGE_STATUS_PLAN_ZZ = '@SETTING_PASSWORD_PLAN/CHANGE_STATUS_PLAN_ZZ'
export const APPLY_PLAN_ZZ = '@SETTING_PASSWORD_PLAN/APPLY_PLAN_ZZ'
export const RESET_STATE_PASSWORD = '@SETTING_PASSWORD_PLAN/RESET_STATE_PASSWORD'
