export const LOAD_COURSE_CATEGORIES = '@COURSE/LOAD_COURSE_CATEGORIES'
export const LOAD_COURSE_CATEGORIES_SUCCESS = '@COURSE/LOAD_COURSE_CATEGORIES_SUCCESS'
export const LOAD_COURSE_CATEGORIES_ERROR = '@COURSE/LOAD_COURSE_CATEGORIES_ERROR'

export const CREATE_COURSE_CATEGORIES = '@COURSE/CREATE_COURSE_CATEGORIES'
export const CREATE_COURSE_CATEGORIES_SUCCESS = '@COURSE/CREATE_COURSE_CATEGORIES_SUCCESS'
export const CREATE_COURSE_CATEGORIES_ERROR = '@COURSE/CREATE_COURSE_CATEGORIES_ERROR'

export const LOAD_COURSE_CATEGORY_DETAIL = '@COURSE/LOAD_COURSE_CATEGORY_DETAIL'
export const LOAD_COURSE_CATEGORY_DETAIL_SUCCESS = '@COURSE/LOAD_COURSE_CATEGORY_DETAIL_SUCCESS'
export const LOAD_COURSE_CATEGORY_DETAIL_ERROR = '@COURSE/LOAD_COURSE_CATEGORY_DETAIL_ERROR'

export const EDIT_COURSE_CATEGORY_DETAIL = '@COURSE/EDIT_COURSE_CATEGORY_DETAIL'
export const EDIT_COURSE_CATEGORY_DETAIL_SUCCESS = '@COURSE/EDIT_COURSE_CATEGORY_DETAIL_SUCCESS'
export const EDIT_COURSE_CATEGORY_DETAIL_ERROR = '@COURSE/EDIT_COURSE_CATEGORY_DETAIL_ERROR'

export const DELETE_COURSE_CATEGORIES = '@COURSE/DELETE_COURSE_CATEGORIES'
export const DELETE_COURSE_CATEGORIES_SUCCESS = '@COURSE/DELETE_COURSE_CATEGORIES_SUCCESS'
export const DELETE_COURSE_CATEGORIES_ERROR = '@COURSE/DELETE_COURSE_CATEGORIES_ERROR'

export const LOAD_ALL_COURSE_CATEGORIES = '@COURSE/LOAD_ALL_COURSE_CATEGORIES'
export const LOAD_ALL_COURSE_CATEGORIES_SUCCESS = '@COURSE/LOAD_ALL_COURSE_CATEGORIES_SUCCESS'
export const LOAD_ALL_COURSE_CATEGORIES_ERROR = '@COURSE/LOAD_ALL_COURSE_CATEGORIES_ERROR'

export const GET_COURSE_CATEGORIES_REORDER = '@COURSE/GET_COURSE_CATEGORIES_REORDER'
export const GET_COURSE_CATEGORIES_REORDER_SUCCESS = '@COURSE/GET_COURSE_CATEGORIES_REORDER_SUCCESS'
export const GET_COURSE_CATEGORIES_REORDER_ERROR = '@COURSE/GET_COURSE_CATEGORIES__ERROR'

export const REORDER_COURSE_CATEGORIES = '@COURSE/REORDER_COURSE_CATEGORIES'
export const REORDER_COURSE_CATEGORIES_SUCCESS = '@COURSE/REORDER_COURSE_CATEGORIES_SUCCESS'
export const REORDER_COURSE_CATEGORIES_ERROR = '@COURSE/REORDER_COURSE_CATEGORIES_ERROR'

export const SAVE_CATEGORY_PREVIEW = '@COURSE/SAVE_CATEGORY_PREVIEW'

export const RESET_COURSE_CATEGORIES = '@COURSE/RESET_COURSE_CATEGORIES'
