export const GET_LIST_TEMPLATE = '@TEMPLATE_MANAGEMENT/GET_LIST_TEMPLATE'
export const GET_TEMPLATE_DETAIL = '@TEMPLATE_MANAGEMENT/GET_TEMPLATE_DETAIL'
export const RESET_LIST_TEMPLATE = '@TEMPLATE_MANAGEMENT/RESET_LIST_TEMPLATE'
